[build]
  command = "npm install cross-env --legacy-peer-deps && npm install --legacy-peer-deps && (npx cross-env EXPO_NO_STATIC_RENDERING=1 expo export --no-static && node fix-deploy.js) || node netlify-deploy.js"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 